dbt_ngpvan:
  outputs:
    dev:
      dbname: dbname
      host: host
      password: password
      port: 5439
      schema: schema
      threads: 4
      type: redshift
      user: username
  target: dev